version: '3'
services:
  server:
    build: .
    ports:
      - "8081:8080"
    depends_on:
      - db
  db:
    image: mysql
    restart: always
    env_file:
      - db.env
    ports:
      - '3307:3306'
    volumes:
      - db:/var/lib/mysql
volumes:
  db:
    driver: local